# Generated by extendr: Do not edit by hand

# nolint start

#' @usage NULL
#' @useDynLib solvephrust, .registration = TRUE
NULL

#' Create an owning pointer to a parsed Rust solver catalog
#'
#' @keywords internal
#' @usage NULL
create_solver <- function(ph_dependent, ph_independent_charges) .Call(wrap__create_solver, ph_dependent, ph_independent_charges)

#' Rust backend for the generic pH solver
#'
#' @keywords internal
#' @usage NULL
solve_generic <- function(solver, temp, ionic_strength, kw, dependent_compounds, independent_compounds, h_i, oh_i) .Call(wrap__solve_generic, solver, temp, ionic_strength, kw, dependent_compounds, independent_compounds, h_i, oh_i)


# nolint end
